Repository DanDHenshaw/Group-6, pull requests merged in 2024-02, with the labels that each got.

#11 Bug fix wallrunning layers
  Assets/_Project/Code/Scripts/Player/PlayerController.cs
  Assets/_Project/Level/Prefabs/Camera/Camera System.prefab
  Assets/_Project/Level/Prefabs/Environment/Square_open_box_prefab.prefab
  Assets/_Project/Level/Prefabs/Environment/long_square_box.prefab
  Assets/_Project/Level/Prefabs/Environment/tall-square_prefab.prefab
  Assets/_Project/Level/Prefabs/Environment/wall_run_prefab.prefab
  Assets/_Project/Level/Prefabs/Player/Player.prefab
  Assets/_Project/Level/Scenes/level 1.unity
  Assets/_Project/Settings/Controls.cs
  Assets/_Project/Settings/Controls.inputactions
  ProjectSettings/TagManager.asset
Labels: bug

#14 Added a timer class in a custom assembly def
  Assets/_Project/Code/Scripts/SpawnSystem/Utilities.meta
  Assets/_Project/Code/Scripts/SpawnSystem/Utilities/Timer.cs
  Assets/_Project/Code/Scripts/SpawnSystem/Utilities/Timer.cs.meta
  Assets/_Project/Code/Scripts/SpawnSystem/Utilities/Utilities.asmdef
  Assets/_Project/Code/Scripts/SpawnSystem/Utilities/Utilities.asmdef.meta
Labels: enhancement

#19 Created States & StateMachine
  Assets/_Project/Code/Scripts/Player/States.meta
  Assets/_Project/Code/Scripts/Player/States/PlayerBaseState.cs
  Assets/_Project/Code/Scripts/Player/States/PlayerBaseState.cs.meta
  Assets/_Project/Code/Scripts/Player/States/PlayerJumpState.cs
  Assets/_Project/Code/Scripts/Player/States/PlayerJumpState.cs.meta
  Assets/_Project/Code/Scripts/Player/States/PlayerLocomotionState.cs
  Assets/_Project/Code/Scripts/Player/States/PlayerLocomotionState.cs.meta
  Assets/_Project/Code/Scripts/StateMachine.meta
  Assets/_Project/Code/Scripts/StateMachine/Predicate.meta
  Assets/_Project/Code/Scripts/StateMachine/Predicate/FuncPredicate.cs
  Assets/_Project/Code/Scripts/StateMachine/Predicate/FuncPredicate.cs.meta
  Assets/_Project/Code/Scripts/StateMachine/Predicate/IPredicate.cs
  Assets/_Project/Code/Scripts/StateMachine/Predicate/IPredicate.cs.meta
  Assets/_Project/Code/Scripts/StateMachine/StateMachine.cs
  Assets/_Project/Code/Scripts/StateMachine/StateMachine.cs.meta
  Assets/_Project/Code/Scripts/StateMachine/States.meta
  Assets/_Project/Code/Scripts/StateMachine/States/IState.cs
  Assets/_Project/Code/Scripts/StateMachine/States/IState.cs.meta
  Assets/_Project/Code/Scripts/StateMachine/Transition.meta
  Assets/_Project/Code/Scripts/StateMachine/Transition/ITransition.cs
  Assets/_Project/Code/Scripts/StateMachine/Transition/ITransition.cs.meta
  Assets/_Project/Code/Scripts/StateMachine/Transition/Transition.cs
  Assets/_Project/Code/Scripts/StateMachine/Transition/Transition.cs.meta
  Assets/_Project/Level/Scenes/Prototype.meta
  Assets/_Project/Level/Scenes/Prototype.unity
  Assets/_Project/Level/Scenes/Prototype/NavMesh.asset
  Assets/_Project/Level/Scenes/Prototype/NavMesh.asset.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement

#21 Grapple Shorten
  Assets/_Project/Code/Scripts/GrapplingGun/GrapplingGun.cs
  Assets/_Project/Code/Scripts/GrapplingGun/GunRotation.cs
  Assets/_Project/Code/Scripts/Player/PlayerController.cs
  Assets/_Project/Level/Prefabs/Camera/Camera System.prefab
  ProjectSettings/TagManager.asset
Labels: bug, enhancement

#24 fixed camera overlay not showing tape measure
  Assets/_Project/Art/Prefabs/Camera/Camera System.prefab
  Assets/_Project/Level/Scenes/level 1.unity
  Packages/manifest.json
  Packages/packages-lock.json
Labels: bug

#26 Feature event system
  Assets/_Project/Art/Prefabs/Enemies.meta
  Assets/_Project/Art/Prefabs/Enemies/Enemy.prefab
  Assets/_Project/Art/Prefabs/Enemies/Enemy.prefab.meta
  Assets/_Project/Code/Prefabs/Player/Player.prefab
  Assets/_Project/Code/Scripts/Enemies.meta
  Assets/_Project/Code/Scripts/Enemies/DetectionStrategy.meta
  Assets/_Project/Code/Scripts/Enemies/DetectionStrategy/ConeDetectionStrategy.cs
  Assets/_Project/Code/Scripts/Enemies/DetectionStrategy/ConeDetectionStrategy.cs.meta
  Assets/_Project/Code/Scripts/Enemies/DetectionStrategy/IDetectionStrategy.cs
  Assets/_Project/Code/Scripts/Enemies/DetectionStrategy/IDetectionStrategy.cs.meta
  Assets/_Project/Code/Scripts/Enemies/EnemyController.cs
  Assets/_Project/Code/Scripts/Enemies/EnemyController.cs.meta
  Assets/_Project/Code/Scripts/Enemies/States.meta
  Assets/_Project/Code/Scripts/Enemies/States/EnemyBaseState.cs
  Assets/_Project/Code/Scripts/Enemies/States/EnemyBaseState.cs.meta
  Assets/_Project/Code/Scripts/Enemies/States/EnemyChaseState.cs
  Assets/_Project/Code/Scripts/Enemies/States/EnemyChaseState.cs.meta
  Assets/_Project/Code/Scripts/Enemies/States/EnemyWanderState.cs
  Assets/_Project/Code/Scripts/Enemies/States/EnemyWanderState.cs.meta
  Assets/_Project/Code/Scripts/Enemies/TargetDetector.cs
  Assets/_Project/Code/Scripts/Enemies/TargetDetector.cs.meta
  Assets/_Project/Code/Scripts/EventSystem.meta
  Assets/_Project/Code/Scripts/EventSystem/Channels.meta
  Assets/_Project/Code/Scripts/EventSystem/Channels/EventChannel.cs
  Assets/_Project/Code/Scripts/EventSystem/Channels/EventChannel.cs.meta
  Assets/_Project/Code/Scripts/EventSystem/Channels/FloatEventChannel.cs
  Assets/_Project/Code/Scripts/EventSystem/Channels/FloatEventChannel.cs.meta
  Assets/_Project/Code/Scripts/EventSystem/Channels/IntEventChannel.cs
  Assets/_Project/Code/Scripts/EventSystem/Channels/IntEventChannel.cs.meta
  Assets/_Project/Code/Scripts/EventSystem/Listeners.meta
  Assets/_Project/Code/Scripts/EventSystem/Listeners/EventListener.cs
  Assets/_Project/Code/Scripts/EventSystem/Listeners/EventListener.cs.meta
  Assets/_Project/Code/Scripts/EventSystem/Listeners/FloatEventListener.cs
  Assets/_Project/Code/Scripts/EventSystem/Listeners/FloatEventListener.cs.meta
  Assets/_Project/Code/Scripts/EventSystem/Listeners/IntEventListener.cs
  Assets/_Project/Code/Scripts/EventSystem/Listeners/IntEventListener.cs.meta
  Assets/_Project/Code/Scripts/HealthSystem.meta
  Assets/_Project/Code/Scripts/HealthSystem/HealthSystem.cs
  Assets/_Project/Code/Scripts/HealthSystem/HealthSystem.cs.meta
  Assets/_Project/Code/Scripts/Player/PlayerController.cs
  Assets/_Project/Code/Scripts/Utilities/Timer.cs
  Assets/_Project/Level/Scenes/Prototype.unity
  Assets/_Project/Scriptable Objects/EventChannels.meta
  Assets/_Project/Scriptable Objects/EventChannels/PlayerHealthPercentage.asset
  Assets/_Project/Scriptable Objects/EventChannels/PlayerHealthPercentage.asset.meta
Labels: enhancement

#28 Fixed Moving Grapple Object
  Assets/_Project/Art/Prefabs/BouncyBall/bouncy ball.prefab
  Assets/_Project/Art/Prefabs/Paper_Planes/Simple_Paper_Plane/paper plane.prefab
  Assets/_Project/Art/Prefabs/wooden car/wooden_car.prefab
  Assets/_Project/Level/Scenes/level 1.unity
Labels: bug

#30 Tutorial level Added
  Assets/_Project/Art/Models/Toaster.meta
  Assets/_Project/Art/Models/Toaster/Firing_Anims.controller
  Assets/_Project/Art/Models/Toaster/Firing_Anims.controller.meta
  Assets/_Project/Art/Models/Toaster/Toaster_Boss_Low_Working (1).fbx
  Assets/_Project/Art/Models/Toaster/Toaster_Boss_Low_Working (1).fbx.meta
  Assets/_Project/Art/Models/Toaster/Toaster_Firing_Animation (1).fbx
  Assets/_Project/Art/Models/Toaster/Toaster_Firing_Animation (1).fbx.meta
  Assets/_Project/Art/Textures/New Material.mat
  Assets/_Project/Art/Textures/New Material.mat.meta
  Assets/_Project/Art/Textures/The Gove.jpeg
  Assets/_Project/Art/Textures/The Gove.jpeg.meta
  Assets/_Project/Art/Textures/Toaster.meta
  Assets/_Project/Art/Textures/Toaster/Toaster_Base_M.mat
  Assets/_Project/Art/Textures/Toaster/Toaster_Base_M.mat.meta
  Assets/_Project/Art/Textures/Toaster/Toaster_Boss_Low_Toaster_Texture_AlbedoTransparency.png
  Assets/_Project/Art/Textures/Toaster/Toaster_Boss_Low_Toaster_Texture_AlbedoTransparency.png.meta
  Assets/_Project/Art/Textures/Toaster/Toaster_Boss_Low_Toaster_Texture_Emission.png
  Assets/_Project/Art/Textures/Toaster/Toaster_Boss_Low_Toaster_Texture_Emission.png.meta
  Assets/_Project/Art/Textures/Toaster/Toaster_Boss_Low_Toaster_Texture_MetallicSmoothness.png
  Assets/_Project/Art/Textures/Toaster/Toaster_Boss_Low_Toaster_Texture_MetallicSmoothness.png.meta
  Assets/_Project/Art/Textures/Toaster/Toaster_Boss_Low_Toaster_Texture_Normal.png
  Assets/_Project/Art/Textures/Toaster/Toaster_Boss_Low_Toaster_Texture_Normal.png.meta
  Assets/_Project/Art/Textures/Toaster/Toaster_M.mat
  Assets/_Project/Art/Textures/Toaster/Toaster_M.mat.meta
  Assets/_Project/Level/Scenes/Tutorial.unity
  Assets/_Project/Level/Scenes/Tutorial.unity.meta
Labels: enhancement

#34 Everything is merged into the scenes and works
  Assets/_Project/Art/Prefabs/Environment/Barricade.prefab
  Assets/_Project/Art/Prefabs/Environment/long close detail.prefab
  Assets/_Project/Art/Prefabs/Environment/square closed detail 1.prefab
  Assets/_Project/Art/Prefabs/Environment/square closed.prefab
  Assets/_Project/Art/Prefabs/Hud/Health Canvas.prefab
  Assets/_Project/Art/Prefabs/merged sections/New Lighting Settings.lighting
  Assets/_Project/Audio.meta
  Assets/_Project/Audio/Music.meta
  Assets/_Project/Code/Prefabs/Enemies/Enemy 1.prefab
  Assets/_Project/Code/Prefabs/Enemies/Enemy 2.prefab
  Assets/_Project/Code/Prefabs/Enemies/Enemy.prefab
  Assets/_Project/Code/Prefabs/Enemies/Toaster.prefab
  Assets/_Project/Code/Prefabs/GameManager.prefab
  Assets/_Project/Code/Prefabs/WaveSystem/SpawnManager.prefab
  Assets/_Project/Code/Scripts/GameManager.cs
  Assets/_Project/Code/Scripts/GrapplingGun/GrapplingGun.cs
  Assets/_Project/Code/Scripts/HealthSystem/HealthSystem.cs
  Assets/_Project/Code/Scripts/Player/PlayerController.cs
  Assets/_Project/Level/Scenes/Hud/Health.unity
  Assets/_Project/Level/Scenes/Hud/MainMenu.unity
  Assets/_Project/Level/Scenes/Hud/Timer.unity
  Assets/_Project/Level/Scenes/Hud/WinScreen.unity
  Assets/_Project/Level/Scenes/Prototype.unity
  Assets/_Project/Level/Scenes/Tutorial.meta
  Assets/_Project/Level/Scenes/Tutorial.unity
  Assets/_Project/Level/Scenes/Tutorial/NavMesh.asset
  Assets/_Project/Level/Scenes/Tutorial/NavMesh.asset.meta
  Assets/_Project/Level/Scenes/level 1.meta
  Assets/_Project/Level/Scenes/level 1.unity
  Assets/_Project/Level/Scenes/level 1/NavMesh.asset
  Assets/_Project/Level/Scenes/level 1/NavMesh.asset.meta
  Assets/_Project/Scriptable Objects/EventChannels/PlayerDamagedEventChannel.asset
  Assets/_Project/Scriptable Objects/EventChannels/PlayerDamagedEventChannel.asset.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/NavMeshAreas.asset
Labels: enhancement

#35 Fixed Health canvas
  Assets/_Project/Code/Scripts/HUD/Health/DamageIndicator.cs
  Assets/_Project/Level/Scenes/Hud/Health.unity
  Assets/_Project/Level/Scenes/Prototype.unity
  Assets/_Project/Level/Scenes/level 1.unity
Labels: enhancement
